app:
  build: ./service-app/
  container_name: tomcat_server
  links:
    - dbsetup
    - db
  ports:
    - "8080:8080"
  volumes:
    - /tmp/war/:/usr/local/tomcat/webapps/
dbsetup:
  build: ./service-dbsetup/
  environment:
    MYSQL_REMOTE_HOST: db
  links:
    - db
db:
  image: mysql
  environment:    
   MYSQL_ROOT_PASSWORD: root
